== Built-in Web Server as testbed

Here I will explain how to launch a HTTP server locally on your machine.

=== Deno is required

On your machine, you need to install link:https://deno.com/[Deno], the next generation JavaScript runtime. Please follow the installation instruction of their site.

I assume you have a bash Terminal where you can do this:

[source,console]
----
$ deno --version
deno 1.43.6 (release, x86_64-apple-darwin)
v8 12.4.254.13
typescript 5.4.5
----

The exact version does not matter. Any recent version will do.

=== Download the project

You can download the zip of this repository from the
link:https://github.com/kazurayam/KS_modify_SendRequestKeyword_with_retry/releases/[Releases] page. Download the latest one, and unzip it.



=== How to start the process

I would write `$PROJECT` to symbolized the directory where you located the project.

In the Terminal command line, do the following operations:

```
$ cd $PROJECT
$ cd webserver
$ /bin/bash ./appstart.sh

Listening on http://localhost:3000/
```

That's it. You can get access to the naughty URL:

- link:http://localhost:3000/naughty[]

The link:https://github.com/kazurayam/KS_modify_SendRequestKeyword_with_retry/blob/develop/webserver/appstart.sh[webserver/appstart.sh] is a single line of shell script:

[source,shell]
----
include::../webserver/appstart.sh[]
----

The `appstart.sh` runs the `deno fun` command while specifying the TypeScript code that makes a HTTP server

- link:https://github.com/kazurayam/KS_modify_SendRequestKeyword_with_retry/blob/develop/webserver/app.ts[webserver/apps.ts]

[quote]
____
It is nice to have a local HTTP server application in a WebUI/WebService Test Automation project. Often, you can mimic the Upplication Under Test with minimum code. I found Deno is a lightweight but full-fledged platform to create a webserver as testbed.
____
